# Site settings
title: Musings of something or another
email: info@jc00ke.com
description: "Technology for good, like yesterday."
baseurl: ""
url: "http://jc00ke.com"
username: jc00ke
timezone: America/Los_Angeles
author: Jesse Cooke

# Build settings
markdown: kramdown
permalink: pretty
sass:
  sass_dir: css

# custom settings
feedurl: "https://feedpress.me/jc00ke"
